Insert Customer
cyntiafelix/SAP-B1-RESTful pull request #3
Opened 2018-10-04 04:47 UTC by cyntiafelix

2018-10-05 16:08 UTC, sacabuche requested changes

2018-10-05 16:08 UTC, sacabuche commented on flask/api/v1/__init__.py
> +api_v1.add_resource(CustomersAPI, '/customers/<function>')
Aca lo ideal es como quotes, y usar los verbos GET, POST, PUT

2018-10-05 16:08 UTC, sacabuche commented on flask/api/v1/sapb1api.py
> +            if function == "insert":
partir estas funciones usando

def post (para crear)
def get (para sacarlo)
def put (para actualizarlo)

2018-10-08 19:57 UTC, cyntiafelix commented on flask/api/v1/__init__.py
> +api_v1.add_resource(CustomersAPI, '/customers/<function>')
Done

2018-10-08 19:58 UTC, cyntiafelix commented on flask/api/v1/sapb1api.py
> +            if function == "insert":
Done

2018-10-08 21:01 UTC, merged